version: '3.4'

services:
  fs.jealje.api:
    image: ${DOCKER_REGISTRY-}fsjealjeapi
    build:
      context: .
      dockerfile: fs.jealje.api/Dockerfile

  sql-server-db:
      container_name: sql-server-db
      image: mcr.microsoft.com/mssql/server
      ports:
         - "1433:1433"
      environment:
        SA_PASSWORD: "admin"
        ACCEPT_EULA: "Y"
